plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.3'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.tourBot'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    /*AI*/
    implementation platform('org.springframework.ai:spring-ai-bom:1.0.5')
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'

    /*DB(vector)*/
    implementation 'org.springframework.ai:spring-ai-starter-vector-store-pgvector'
    implementation 'org.postgresql:postgresql'

    /*elasticsearch*/
    implementation 'co.elastic.clients:elasticsearch-java:8.18.1'

    /*lombok*/
    compileOnly 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'
    testCompileOnly 'org.projectlombok:lombok:1.18.34'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.34'

    /*flywayDB*/
    implementation "org.flywaydb:flyway-core"
    implementation "org.flywaydb:flyway-database-postgresql"

    /*tika(텍스트 추출)*/
    implementation "org.apache.tika:tika-core:2.9.0"
    implementation "org.apache.tika:tika-parsers-standard-package:2.9.0"
}

test {
    useJUnitPlatform()
}