server:
  port: 8090

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        model: text-embedding-3-small
    vectorstore:
      pgvector:
        table-name: vector_store
        initialize-schema: false
        index-type: ivfflat
        distance-type: COSINE_DISTANCE
        dimensions: 1536
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

history:
  url: ${HISTORY_SERVICE_URL}

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: DEBUG

weather:
  api-key: ${OPENWHETHER_API_KEY}

ai:
  prompt:
    orchestrator: |
      You are an AI orchestrator.

      Your role:
      - Decide whether to answer directly or use tools
      
      Rules:
      - If the question requires real-time or up-to-date information, you MUST use a tool.
      - Use getWeather tool for weather information
      - Do NOT guess weather information
      - Use getExchangeRate tool for currency conversion
      - Do NOT guess currency rate information
      - Use rag tool for internal knowledge.
      - use db tool for user-specific data.
      - DO NOT answer from your own knowledge if freshness is important.

      Do NOT use the tool when:
      - The question is simple or common knowledge

      Always choose the best approach.

    recommend-agent: |
      You are a recommendation assistant.

      Your job:
      - Find relevant and up-to-date information
      - Based on the user's request, recommend places, foods, or travel plans;
      - if the user is asking for recommendation of travel plan with best seasons or best months, use search tool and recommend. 
      - Provide concise and factual summaries
      - Avoid hallucinations