server:
  port: 8090

spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
history:
  url: http://history-service:8091

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: DEBUG